### ISSUE TITLE
MDX extension: JSX

### ISSUE THREAD

**Issue by wooorm** [micromark/common-markup-state-machine#13]
MDX support consists of a couple of things:

### Ignore HTML parsing

For MDX to work, “normal” block and inline HTML parsing has to be turned off. As MDX would include autolinks (`<http://example.com>`: <http://example.com>), it is probably better to split the [HTML or autolink](https://github.com/micromark/common-markup-state-machine#1118-html-or-autolink-less-than-after-state) states in two and support split points / retreating / branching

### Interleaving

Markdown is whitespace sensitive, line-by-line, whereas JSX is whitespace insensitive, and well, not line-by-line.
There is a WIP, not very maintained, [spec for JSX](https://github.com/facebook/jsx), which we could properly parse, but this leaves the question open whether we support JSX in its entirety, such as this weird example:

**Exhibit A**: 

```jsx 
<Dropdown x={1 /**/ + 2}
> /*
  A dropdown list */

  <Menu> // some stuff
  
  	<MenuItem>Do Something</MenuItem>

  </Menu>
</Dropdown>

```

^-- Note blank lines, indentation, weird comments, etc?

### Errors (“invalid” JSX)

JS(X) also has errors, of course, do we throw errors? Do we continue parsing?

**Exhibit B**: 

```
<Dropdown x={} />
```

```
<Dropdown>
  A dropdown list
  <Menu><MenuItem>Do Something</MenuItem></Menu>

# Heading
```

### Exposing nodes

Currently, MDX exposes a literal for JSX nodes: `{type: 'jsx', value: '<Dropdown>…</Dropdown>'}`. What if we’d expose the JSX tree similar to how Acorn/Babel would parse the JSX?

---

/cc @johno

**Comment by ChristianMurphy** [comment]
Exhibit C: Fragments and inline property access

```jsx
<>
  {props.name}
</>
```

**Comment by wooorm** [comment]
Wrote about how to parse MDX here https://github.com/micromark/mdx-state-machine, which essentially is everything needed to support MDX in a Markdown parser (and specifically made for CMSM), so I’ll close this.
