### ISSUE TITLE
incremental parsing

### ISSUE THREAD

**Issue by ghost** [micromark/common-markup-state-machine#14]
Hello! :wave: First of all, I’d like to let y’all know that I really appreciate your work towards evolving Markdown.

I am not sure whether this issue is appropriate on this repo, or whether it should go on the `micromark` repo.

I have found this project while looking for ways to highlight Markdown syntax in a way compliant to CommonMark. Again, it’s really neat, and I appreciate your work towards it!

However, for this use‐case, something that appears to be missing is the ability to perform partial modifications to Markdown source. It doesn’t really matter that much to me if it take a while to highlight a large document for the first time, but it would be ideal if subsequent modifications could be performed rapidly.

I was wondering whether it’d make sense and be possible to account for that kind of use‐case, or if it is out of scope for this project.

Another interesting project is [ToastMark] by the Toast UI team. The problem I found with it, though, is that it produces AST, which makes it kinda awkward to use it for syntax highlighting. It also appears to not be very customizable, so one wouldn’t be able to e.g. remove GFM extensions, or use other kinds of plugins.

[ToastMark]: https://ui.toast.com/weekly-pick/en_20200402/

**Comment by ChristianMurphy** [comment]
There was some discussion of incremental parsing at https://github.com/micromark/micromark/issues/8#issuecomment-527980323
@wooorm is working on a new version of the Micromark parser, he may be able to comment better on whether incremental parsing is still in scope.

This repo is mostly spec, not implementation, it sounds like you are interested in an implementation of an incremental markdown parser?
If so it may sense to continue this at https://github.com/micromark/micromark

**Comment by ghost** [comment]
> This repo is mostly spec, not implementation, it sounds like you are interested in an implementation of an incremental markdown parser?

I imagined that a change in the spec might have been necessary to accomodate for incremental parser implementations, or at least to facilitate it somehow.

If you think this fits better on the micromark repo, [you might be able to transfer this issue there][transfering issues] depending on your permissions on both repositories.

[transfering issues]: https://help.github.com/en/github/managing-your-work-on-github/transferring-an-issue-to-another-repository

**Comment by wooorm** [comment]
CM compliance is at odds with incremental parsing, as something on the first line of the document could affect the last line. Or something at the start of a paragraph could affect the end. As the thread Christian linked to explains in more detail.

> I imagined that a change in the spec might have been necessary to accomodate for incremental parser implementations, or at least to facilitate it somehow.

That would make it no longer compatible with commonmark though 🤔

**Comment by ghost** [comment]
> […] something on the first line of the document could affect the last line.

That’s true, but the cases you had mentioned are kinda edge cases in my opinion. Very rarely will people have documents that look like those, and in those circumstances, it’d make sense and be fine to have to reparse as much as necessary.

> […] something at the start of a paragraph could affect the end.

In my opinion, incremental parsing only really needs to be done at the block level. For the inline level, it feels a bit unnecessary/overkill.

- - -

The actually problematic thing (which I didn’t see mentioned in that thread) is related to reference links. Ideally, if someone adds a new reference to the document, a paragraph would only need to be reparsed if it contains potential links whose target would have been that reference (if it had been present earlier, that is).

The problem is that it’s not clear to me whether it’s easy to parse potential link references beforehand that way.

**Comment by ChristianMurphy** [comment]
@Zambonifofex there's a distinction here between implementation and spec.
This spec focuses on completeness and correctness, and as @wooorm mentioned the commonmark spec that this builds on, has several features which are at odds with incremental parsing.
Including reference links as you mention.

At an implementation level parsers may subtly diverge from the spec, to support faster parsing avoiding excessive backtracking or lookahead.
For example this incremental commonmark parser: https://github.com/ikatyang/tree-sitter-markdown
notes:
> Note: This grammar is based on the assumption that link label matchings will never fail since reference links can come before their reference definitions, which causes it hard to do incremental parsing without this assumption.

**Comment by wooorm** [comment]
Going to close this because the conversation seems resolved.

I don’t think I’ll document incremental parsing here, as it deviates from CommonMark, and I’m not interesting in doing that.

For whether people want to skip this case and implement it differently in their parsers, I’m fine with that and I find it quite understandable!
