### ISSUE TITLE
The thing between the tokeniser and an adapter

### ISSUE THREAD

**Issue by wooorm** [micromark/common-markup-state-machine#7]
##### Terms

(tokeniser: the thing currently specced, that emits tokens; adapter: a thing that consumes events and produces e.g. an HTML string or a ST, wording WIP).

##### Problem

We need something that knows that we are already in a blockquote, that a lazy continuation line belongs to the content in that blockquote.
The tokeniser should deal with creating tokens, not with opening and closing blocks.
These two will integrate together though.
The HTML spec has a [tokeniser](https://html.spec.whatwg.org/multipage/parsing.html#tokenization) and a [tree construction](https://html.spec.whatwg.org/multipage/parsing.html#tree-construction) mechanism.
Tree construction (as in, an AST or a CST) is something that can sit above micromark.

So what’s between the tokens and syntax-trees or an HTML string? What does it look like?

##### Example

Say we’d have this markup (note the superfluous whitespace at the start, and ␠ is a space):

```markdown
  > # asd #
  > para␠␠
  graph
```

The current state machine creates (or will create) something along these lines (token type, offset start and end in curlies, and value in parens):

```
whitespace {0, 2} (`  `)
marker {2, 3} (`>`)
whitespace {3, 4} (` `)
sequence {4, 5} (`#`)
whitespace {5, 6} (` `)
content {6, 9} (`asd`)
whitespace {9, 10} (` `)
sequence {10, 11} (`#`)
lineTerminator {11, 12} (`\n`)
whitespace {0, 2} (`  `)
marker {2, 3} (`>`)
whitespace {3, 4} (` `)
content {4, 8} (`para`)
whitespace {8, 10} (`  `)
lineTerminator {10, 11} (`\n`)
whitespace {0, 2} (`  `)
content {2, 7} (`graph`)
lineTerminator {7, 8} (`\n`)
end-of-file
```

A CST for that, would look something along these lines (just an idea, not the thing to discussed here):

```
document
  blockquote
    atxHeading
      lineStart
        whitespace {0, 2} (`  `)
        marker {2, 3} (`>`)
        whitespace {3, 4} (` `)
        fence
          sequence {4, 5} (`#`)
          whitespace {5, 6} (` `)
      phrasing
        text {6, 9} (`asd`)
      lineEnd
        fence
          whitespace {9, 10} (` `)
          sequence {10, 11} (`#`)
        lineTerminator {11, 12} (`\n`)
    paragraph
      lineStart
        whitespace {0, 2} (`  `)
        marker {2, 3} (`>`)
        whitespace {3, 4} (` `)
      phrasing
        text {4, 8} (`para`)
        hard-break
          line-end
            whitespace {8, 10} (`  `)
            lineTerminator {10, 11} (`\n`)
          lineStart
            whitespace {0, 2} (`  `)
        text {2, 7} (`graph`)
      lineEnd
        lineTerminator {7, 8} (`\n`)
```

What does the thing between the tokens and this tree (or an HTML string) look like?

**Comment by ChristianMurphy** [comment]
What would the intermediate format be used for?
We already have several intermediate format, a tokenizer output, a CST, an AST.
What is the expected value-add of this new format?

**Comment by wooorm** [comment]
After some more thinking the last week I’ve got a better picture of it in my head, beautifully displayed in this work of art:

```ascii
+---------------+                       +---------------+
|               | -> 1. tokens -------> |               | -> 5. “events”?
|               | (whitespace,          |               |  (open content,
|               |   marker,             |               |  open definition,
|               |   content)            |               |    open label,
|               |                       |               |    whitespace,
|               | -> 2. signals ------> |               |      content,
|               | (html-comment,        |               |    whitespace,
|               |  not-a-definition)    |               |   close label…)
| state machine |                       |   the thing   |   |
|               | <--- 3. characters <- |               |   v
|               |  (here have some more |               |   |
|               |           characters) |               |   |
|               |                       |               |   |
|               | <----- 4. “state”? <- |               |   |
|               | (yup, we can enter    |               |   |
|               | indented code; nope,  |               |   |
+---------------+     not a blockquote) +---------------+   |
                                                            |
                                         +---------+--------+
                                         |         |        |
                                         v         v        v
                                      +------+  +-----+  +-----+
                                      | HTML |  | CST |  | AST |
                                      +------+  +-----+  +-----+
```

So I see them as tightly coupled.
Having this thing reduces knowledge in the state machine by moving it to itself. Having that knowledge somewhere means HTML/CST/AST don’t need to each implement it.
Maybe this thing is called a lexer?

**Comment by ChristianMurphy** [comment]
A few follow up questions

1. What is the difference between a token  (1 in chart) and a signal (2 in chart)?
2. characters (3 in chart), where are these coming from? Would this content source would act as a second document getting merged into the characters being processed in the state machine?
3. state (4 in chart), maybe it's just the name, but passing state from "the thing" into the "state machine" seems strange architecturally, like we've split the state machine in half.
4. I'm curious about "the thing" flowing directly into HTML, CST, and AST. I was under the impression that micromark/remark would produce only a CST. And that other formats (AST, HTML) would be derived from the CST?

**Comment by ChristianMurphy** [comment]
> Maybe this thing is called a lexer?

Many pieces of software implement the lexer and parser as one, hence why the term is often used interchangeably.
When they are separated, the lexer takes text and categorizes chunks of text, the parser converts the categorized token stream into a syntax tree. ([reference 1](https://stackoverflow.com/questions/2842809/lexers-vs-parsers), [reference 2](https://www.quora.com/What-is-the-difference-between-a-lexer-and-a-parser))

**Comment by wooorm** [comment]
> 1. What is the difference between a token (1 in chart) and a signal (2 in chart)?

Tokens are data from the input, such as a couple of whitespace characters, a link label marker (`[`), and some content characters (`qwerty`) etc. “Signals” are semantic information `definition-label-open`, which lets “the thing” construct things, or know that it needs to wait a bit longer!

> 2. characters (3 in chart), where are these coming from? Would this content source act as a second document getting merged into the characters being processed in the state machine?

[Characters](https://github.com/micromark/common-markup-state-machine#3-characters) are actual characters in the input, and a couple of “conceptual” characters (such as end-of-file).
They come over the network or from the file system, with “the thing” in between, that buffers some more, or drops the buffer, and so feeds the tokeniser.

> 3. state (4 in chart), maybe it's just the name, but passing state from "the thing" into the "state machine" seems strange architecturally, like we've split the state machine in half.

I see it more as that “the thing” collects information about the point we are currently at: in a HTML block, in a list, etc. And the tokeniser can access that information: well, if we’re in an HTML block, that means we can’t start fenced code.

> 4. I'm curious about "the thing" flowing directly into HTML, CST, and AST. I was under the impression that micromark/remark would produce only a CST. And that other formats (AST, HTML) would be derived from the CST?

Interesting! So my idea is for micromark to stream events, instead of building a whole CST in memory. These “adapters” for micromark then build that into an output format, a CST / AST in the case of remark, or directly to HTML!

---

Extra:

> When they are separated, the lexer takes text and categorizes chunks of text, the parser converts the categorized token stream into a syntax tree. (reference 1, reference 2)

Ah, so I see the parser as both the tokeniser/state-machines and “the thing”.
“The thing” is called tree construction in HTML. It’s a nuanced difference, something like these events:

```
blockquote open
`>`
paragraph open
`asd`
paragraph close
blockquote close
```

Versus what I see as tree construction:

```
{type: 'blockquote', children: [{type: 'paragraph', children: [{type: 'text', value: 'asd'}]}]}
```

So I see micromark as a parser, but the last step is very close to tree construction, something else does that

**Comment by ChristianMurphy** [comment]
Thanks for that additional context, that makes more sense.
That distinction is pretty fine grained.

Is this included for the sake of completeness?
Or is this something that is intended for adopters to specifically implement these separately?

**Comment by wooorm** [comment]
> Is this included for the sake of completeness?

I’m a firm believer in syntax trees (remark), but I do also see value in the common case of doing only markdown -> HTML (let’s say project XXX), which should be tiny and fast. “The thing”, as an interface of micromark, should make this divide possible (haven’t thought about this for a couple of months 😅 so I may say different things now than before) 

I want to provide a clear layer where syntax extensions can hook into, used in both remark and XXX. And I think it’s good architecturally to break remark/transformers/etc away from these syntax extensions.

remark is now at 91% of downloads of marked on npm, slowly getting closer, I’m thinking this year surpassing it. But remark and marked are not the synonyms. I think that XXX should exist as an alternative to marked, so remark can do other things!

Not sure if “we”, as in unified, should make this, but it should be possible to build it on top of micromark.

**Comment by wooorm** [comment]
This is solved in micromark. I’ll add more on how it works in cmsm later.
